// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/src/main/proto/cogrpc.proto

package link.relaynet.grpctest.cogrpc;

public final class Cogrpc {
  private Cogrpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_relaynet_cogrpc_CargoDelivery_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_relaynet_cogrpc_CargoDelivery_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_relaynet_cogrpc_CargoDeliveryAck_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_relaynet_cogrpc_CargoDeliveryAck_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037app/src/main/proto/cogrpc.proto\022\017relay" +
      "net.cogrpc\"*\n\rCargoDelivery\022\n\n\002id\030\001 \001(\t\022" +
      "\r\n\005cargo\030\002 \001(\014\"\036\n\020CargoDeliveryAck\022\n\n\002id" +
      "\030\001 \001(\t2\272\001\n\nCargoRelay\022U\n\014DeliverCargo\022\036." +
      "relaynet.cogrpc.CargoDelivery\032!.relaynet" +
      ".cogrpc.CargoDeliveryAck(\0010\001\022U\n\014CollectC" +
      "argo\022!.relaynet.cogrpc.CargoDeliveryAck\032" +
      "\036.relaynet.cogrpc.CargoDelivery(\0010\001B!\n\035l" +
      "ink.relaynet.GRPCtest.cogrpcP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_relaynet_cogrpc_CargoDelivery_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_relaynet_cogrpc_CargoDelivery_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_relaynet_cogrpc_CargoDelivery_descriptor,
        new java.lang.String[] { "Id", "Cargo", });
    internal_static_relaynet_cogrpc_CargoDeliveryAck_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_relaynet_cogrpc_CargoDeliveryAck_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_relaynet_cogrpc_CargoDeliveryAck_descriptor,
        new java.lang.String[] { "Id", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
